### ISSUE TITLE
Why do you hide the code that generates the graphs?

### ISSUE THREAD

**Issue by corneliusroemer** [nschloe/hotware#49]
I wanted to see how you generate the graphs, maybe fork and tinker - but it seems like the repo with the relevant code is private. I'm curious why! Is that on purpose?

https://github.com/nschloe/trends-dev/

**Comment by nschloe** [comment]
Hi Cornelius, I haven't quite decided yet what to do with the code, that's why it's not available here. I might open-source it at some point.
